/*
    This library is licensed under the BSL1.0 (Boost Software License) license:

    Boost Software License - Version 1.0 - August 17th, 2003

    Copyright AREStudio 2026

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef UTILS_H
#define UTILS_H

#include <allegro5/allegro.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float juego_w;
    float juego_h;
    float scale;
    float offset_x;
    float offset_y;
    int clip_orig_x, clip_orig_y, clip_orig_w, clip_orig_h;
    ALLEGRO_TRANSFORM trans_juego;
    ALLEGRO_TRANSFORM trans_original;
} UtilsBox;

static inline UtilsBox utilsbox_create(float juego_w, float juego_h) {
    UtilsBox box;
    box.juego_w = juego_w;
    box.juego_h = juego_h;
    box.scale = 1.0f;
    box.offset_x = 0.0f;
    box.offset_y = 0.0f;
    al_identity_transform(&box.trans_juego);
    al_identity_transform(&box.trans_original);
    return box;
}

static inline void utilsbox_update(UtilsBox *box, float ventana_w, float ventana_h) {
    if (!box) return;
    float scale_x = ventana_w / box->juego_w;
    float scale_y = ventana_h / box->juego_h;
    box->scale = (scale_x < scale_y) ? scale_x : scale_y;
    box->offset_x = (ventana_w - (box->juego_w * box->scale)) / 2.0f;
    box->offset_y = (ventana_h - (box->juego_h * box->scale)) / 2.0f;
    al_identity_transform(&box->trans_juego);
    al_scale_transform(&box->trans_juego, box->scale, box->scale);
    al_translate_transform(&box->trans_juego, box->offset_x, box->offset_y);
}

static inline void utilsbox_begin(UtilsBox *box) {
    if (!box) return;
    const ALLEGRO_TRANSFORM *actual = al_get_current_transform();
    if (actual) box->trans_original = *actual;
    al_get_clipping_rectangle(&box->clip_orig_x, &box->clip_orig_y, &box->clip_orig_w, &box->clip_orig_h);
    al_set_clipping_rectangle((int)box->offset_x, (int)box->offset_y, (int)(box->juego_w * box->scale), (int)(box->juego_h * box->scale));
    al_use_transform(&box->trans_juego);
}

static inline void utilsbox_end(UtilsBox *box) {
    if (!box) return;
    al_use_transform(&box->trans_original);
    al_set_clipping_rectangle(box->clip_orig_x, box->clip_orig_y, box->clip_orig_w, box->clip_orig_h);
}

static inline void utilsbox_mouse_transform(UtilsBox *box, int mouse_x, int mouse_y, float *juego_x, float *juego_y) {
    if (!box || !juego_x || !juego_y) return;
    *juego_x = ((float)mouse_x - box->offset_x) / box->scale;
    *juego_y = ((float)mouse_y - box->offset_y) / box->scale;
}

#ifdef __cplusplus
}
#endif

#endif